apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: { .Values.replicaCount }
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 3000
        resources: { .Values.resources }
