apiVersion: v2
name: jrunner
version: 0.1.0
description: A Helm chart for deploying jrunner components

dependencies:
  - name: api
    version: 0.1.0
    repository: "file://api/helm"
  #- name: web
  #  version: 0.1.0
  #  repository: "file://charts/web"
  #- name: worker
  #  version: 0.1.0
  #  repository: "file://worker/helm"