---
apiVersion: skaffold/v3
kind: Config
metadata:
  name: jrunner

build:
  artifacts:
  - image: jrunner-api
    context: ./api
    docker:
      dockerfile: Dockerfile
  - image: jrunner-worker
    context: ./worker
    docker:
      dockerfile: Dockerfile
  - image: jrunner-web
    context: ./web
    docker:
      dockerfile: Dockerfile

deploy:
  helm:
    releases:
    - name: jrunner
      namespace: jrunner
      createNamespace: true
      chartPath: ./helm
      setValueTemplates:
        api.image.repository: "{{ .IMAGE_REPO_jrunner_api }}"
        api.image.tag: "{{ .IMAGE_TAG_jrunner_api }}"
        worker.image.repository: "{{ .IMAGE_REPO_jrunner_worker }}"
        worker.image.tag: "{{ .IMAGE_TAG_jrunner_worker }}"
        web.image.repository: "{{ .IMAGE_REPO_jrunner_api }}"
        web.image.tag: "{{ .IMAGE_TAG_jrunner_api }}"
      valuesFiles: 
        - .dev/values-jrunner.yaml

profiles:
  - name: docker-desktop
    activation:
      - kubeContext: docker-desktop
        command: dev