---
apiVersion: skaffold/v3
kind: Config
metadata:
  name: jrunner

build:
  artifacts:
  - image: jrunner-api
    context: ./api
    docker:
      dockerfile: Dockerfile
  - image: jrunner-worker
    context: ./worker
    docker:
      dockerfile: Dockerfile

manifests:
  rawYaml:
    - .dev/secret.yaml

deploy:
  kubectl: {}
  helm:
    releases:
    - name: mongodb
      namespace: jrunner
      createNamespace: true
      remoteChart: oci://registry-1.docker.io/bitnamicharts/mongodb
      version: 16.4.3
      valuesFiles: 
        - .dev/values-mongodb.yaml
    - name: minio
      namespace: jrunner
      createNamespace: true
      remoteChart: oci://registry-1.docker.io/bitnamicharts/minio
      version: 15.0.2
      valuesFiles: 
        - .dev/values-minio.yaml
    #- name: jrunner
    #  namespace: jrunner
    #  createNamespace: true
    #  chartPath: ./helm
    #  valuesFiles: 
    #    - .dev/values.yaml


profiles:
  - name: docker-desktop
    activation:
      - kubeContext: docker-desktop
        command: dev