---
apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: jrunner

build:
  artifacts:
  - image: jrunner-api
    context: ./api
    docker:
      dockerfile: Dockerfile
  - image: jrunner-worker
    context: ./worker
    docker:
      dockerfile: Dockerfile

deploy:
  helm:
    releases:
    - name: jrunner-api
      namespace: jrunner
      createNamespace: true
      chartPath: api/helm
      setValues:
        image.repository: jrunner-api
        env[0].name: MONGO_HOST
        env[0].value: "mongodb"
        env[1].name: MONGO_PORT
        env[1].value: "27017"
        env[2].name: MONGO_DB_NAME
        env[2].value: "jrunner"
        env[3].name: MONGO_DB_USER
        env[3].value: "myuser"
        env[4].name: MONGO_DB_PASS
        env[4].value: "mypassword"
        env[5].name: S3_URL
        env[5].value: "https://s3.cbar.az"
        env[6].name: S3_ACCESS_KEY
        env[6].value: "sWN8vFdS4sXloyDXApdO"
        env[7].name: S3_SECRET_KEY
        env[7].value: "cHat4VLoAebDW8wCMWAMlP5vMFXSxNOFmYtDBgLD"
        env[8].name: S3_BUCKET
        env[8].value: "jrunner"

portForward:
- resourceType: deployment
  resourceName: jrunner-api
  namespace: default
  port: 8000
  localPort: 8000

profiles:
  - name: docker-desktop
    activation:
      - kubeContext: docker-desktop
        command: dev
