---
apiVersion: skaffold/v3
kind: Config
metadata:
  name: jrunner

build:
  artifacts:
  - image: jrunner-api
    context: ./api
    docker:
      dockerfile: Dockerfile
  - image: jrunner-worker
    context: ./worker
    docker:
      dockerfile: Dockerfile

deploy:
  kubectl: {}
  helm:
    releases:
    - name: jrunner
      namespace: jrunner
      createNamespace: true
      chartPath: ./helm
      valuesFiles: 
        - .dev/values.yaml


profiles:
  - name: docker-desktop
    activation:
      - kubeContext: docker-desktop
        command: dev