[supervisord]
nodaemon=true
user=root
logfile=/dev/stdout
logfile_maxbytes = 0
loglevel=error
logformat=%(asctime)s %(levelname)s [%(process)s] %(message)s
pidfile=/var/run/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
logfile_maxbytes = 0
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0
process_name=%(program_name)s

[program:api]
command=python main.py
directory=/app/api
autostart=true
autorestart=true
logfile_maxbytes = 0
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0
process_name=%(program_name)s
