[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes = 0
pidfile=/var/run/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
logfile_maxbytes = 0
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0
process_name=%(program_name)s

[program:api]
command=fastapi run
directory=/app/api
autostart=true
autorestart=true
logfile_maxbytes = 0
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0
process_name=%(program_name)s

[program:worker]
command=python main.py
directory=/app/worker
autostart=true
autorestart=true
logfile_maxbytes = 0
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0
process_name=%(program_name)s
