replicaCount: 1

image:
  repository: jrunner-api
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []

env: []

envFromSecret: ""

podAnnotations: {}

podLabels: {}

podSecurityContext: {}

securityContext: {}

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}