{{- if .Values.limits.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: kubeblast-limits
  namespace: {{ .Release.Namespace }}
spec:
  limits:
  - default:
      cpu: {{ .Values.limits.defaultCpu }}
      memory: {{ .Values.limits.defaultMemory }}
    defaultRequest:
      cpu: {{ .Values.limits.defaultCpu }}
      memory: {{ .Values.limits.defaultMemory }}
    type: Container
{{- end }}
