{{- if not .Values.pvc.existingClaim }}
{{- $pvcName := include "kubeblast.fullname" . }}
{{- if not (lookup "v1" "PersistentVolumeClaim" .Release.Namespace $pvcName) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $pvcName }}
  labels:
    {{- include "kubeblast.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.pvc.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  accessModes:
    - {{ .Values.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
{{- end }}
{{- end }}
