---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: '{{ include "kubeblast.fullname" . }}'
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "create"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["resourcequotas"]
    verbs: ["create", "update", "get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["create", "delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: '{{ include "kubeblast.fullname" . }}'
subjects:
  - kind: ServiceAccount
    name: '{{ include "kubeblast.fullname" . }}'
roleRef:
  kind: Role
  name: '{{ include "kubeblast.fullname" . }}'
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ include "kubeblast.fullname" . }}-cluster-read'
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: '{{ include "kubeblast.fullname" . }}-cluster-read'
subjects:
  - kind: ServiceAccount
    name: '{{ include "kubeblast.fullname" . }}'
    namespace: '{{ .Release.Namespace }}'
roleRef:
  kind: ClusterRole
  name: '{{ include "kubeblast.fullname" . }}-cluster-read'
  apiGroup: rbac.authorization.k8s.io
