apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeblast.fullname" . }}
  labels:
    {{- include "kubeblast.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port.web }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    {{- include "kubeblast.selectorLabels" . | nindent 4 }}