apiVersion: v1
kind: Service
metadata:
  name: {{ include "jrunner.fullname" . }}
  labels:
    {{- include "jrunner.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "jrunner.selectorLabels" . | nindent 4 }}