apiVersion: v1
kind: Service
metadata:
  name: {{ include "jrunner-api.resourceName" . }}
  labels:
    {{- include "jrunner.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "jrunner-api.selectorLabels" . | nindent 4 }}