apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: { .Values.replicaCount }
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
        resources: { .Values.resources }
