apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-worker"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-worker"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-worker"
    spec:
      containers:
      - name: worker
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
          {{- toYaml .Values.env | nindent 12 }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}