---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "AAA.fullname" . }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "delete", "get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "AAA.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "AAA.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "AAA.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
 