image:
  repository: jrunner-worker
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []

env: []

envFromSecret: ""

podAnnotations: {}

podLabels: {}

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}