apiVersion: apps/v1
kind: Deployment
metadata:
  name: jrunner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jrunner
  template:
    metadata:
      labels:
        app: jrunner
    spec:
      serviceAccountName: jrunner
      containers:
      - name: jrunner
        image: jrunner
        imagePullPolicy: Never
        ports:
        - containerPort: 8000