apiVersion: batch/v1
kind: Job
metadata:
  name: jrunner-job
  labels:
    jrunner-job: "teymur"
spec:
  template:
    metadata:
      name: jrunner-job
    spec:
      containers:
      - name: example-container
        image: busybox
        command: ["sleep", "60m"]
      restartPolicy: Never