enabled: true
instanceName: "kubeblast-mongodb"
username: "kubeblast"
password: "kubeblast"
database: "kubeblast"
imagePullPolicy: "IfNotPresent"
imagePullSecrets: []
resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
persistence:
  enabled: true
  size: "2Gi"
  accessMode: "ReadWriteOnce"
  storageClassName: ""
  annotations: {}
  labels: {}
extraVolumes: []
extraVolumeMounts: []