apiVersion: apps/v1
kind: Deployment
metadata:
  name: jrunner-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jrunner-api
  template:
    metadata:
      labels:
        app: jrunner-api
    spec:
      serviceAccountName: jrunner
      containers:
      - name: jrunner-api
        image: jrunner-api
        imagePullPolicy: Never
        ports:
        - containerPort: 8000