version: '3.8'

networks:
  shared_network:
    driver: bridge

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    hostname: minio.local
    networks:
      shared_network:
        aliases:
          - minio.local
    ports:
      - "9000:9000" # MinIO API port
      - "9090:9090" # MinIO Console port
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: root
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9090"

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    hostname: mongodb.local
    networks:
      shared_network:
        aliases:
          - mongodb.local
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb_data:/data/db

volumes:
  minio_data:
    driver: local
  mongodb_data:
    driver: local