# helm install minio oci://registry-1.docker.io/bitnamicharts/minio -f .dev/values-minio.yaml --namespace jrunner --create-namespace

mode: standalone
auth:
  rootUser: admin
  rootPassword: Root12345!
persistence:
  enabled: true
service:
  type: NodePort
  nodePorts:
    console: "30090"
