# helm install mongodb oci://registry-1.docker.io/bitnamicharts/mongodb -f .dev/values-mongodb.yaml --namespace jrunner --create-namespace

auth:
  enabled: true
  rootPassword: Root12345!
  usernames:
    - "jrunner"
  passwords:
    - "jrunner"
  databases:
    - "jrunner"
persistence:
  enabled: true 
service:
  type: NodePort
  nodePorts:
    mongodb: 30017