apiVersion: v2
name: jrunner-api
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: minio
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 15.0.2
    condition: minio.enabled