fullnameOverride: ""

global:
  imagePullSecrets: []
  imagePullPolicy: IfNotPresent
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

api:
  env: []
  envFromSecret: ""
  podAnnotations: {}
  podLabels: {}

  image:
    repository: jrunner
    tag: latest
  service:
    type: ClusterIP
    port: 8000
    nodePort: ""
  ingress:
    enabled: false
    annotations: {}
    className: ""
    host: ""
  serviceAccount:
    create: true
    annotations: {}
    name: ""
  resources: {}

worker:
  image:
    repository: jrunner-worker
    tag: latest
  resources: {}

web:
  env: []
  envFromSecret: ""
  podAnnotations: {}
  podLabels: {}
  image:
    repository: jrunner
    tag: latest
  service:
    type: ClusterIP
    port: 8000
    nodePort: ""
  ingress:
    enabled: false
    annotations: {}
    className: ""
    host: ""
  resources: {}