apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: { .Values.replicaCount }
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8000
        resources: { .Values.resources }
