server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html =404;
    }

    # Static assets (JS, CSS, images, etc.)
    location /static/ {
        alias /usr/share/nginx/html/static/;
        try_files $uri =404;
        # Optional: Cache static assets for 6 months
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }

    location ~* \.(?:ico|woff2?|eot|ttf|otf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
